- name: Discord Commits
        uses: Sniddl/discord-commits@v1.3
        with:
          webhook: ${{ https://discord.com/api/webhooks/955152057269121025/RNfDRtC531d1zNUUC2JXFwRc10FkQJZQq0t5qOIFi8ahv7_7vUwlAq2o8ZncUbH-CGdu }}
          message: "Hallo, dit is een test."
          embed: '{ "title": "{{ commit.title }}", "description": "{{ commit.description }}", "url": "{{ commit.url }}", "author": { "name": "{{ commit.author.name }} ({{ commit.author.username }})", "icon_url": "https://avatars.io/gravatar/{{ commit.author.email }}"} }'
          last-commit-only: false
